# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 01:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='product_images', verbose_name='Images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('coverImage', models.ImageField(blank=True, upload_to='product_images')),
                ('contact_Name', models.CharField(blank=True, max_length=128)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('product_location', models.CharField(blank=True, max_length=128)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('Fb_url', models.CharField(blank=True, max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
